import Head from "next/head";
import Footer from "../components/Footer/Footer";
import Header from "../components/Header/Header";
import MainContent from "../components/MainContent/MainContent";
import SignUpSection from "../components/SignUpSection/SignUpSection";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fylo Dark Theme landing page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/joseph.ico" />
      </Head>

      {/* <body> */}
      <Header />
      <MainContent />
      <SignUpSection />
      <Footer />
      {/* </body> */}
    </div>
  );
}
