import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import logo from "../images/logo.svg";
import iconAccessAnywhere from "../images/icon-access-anywhere.svg";
import iconAnyFile from "../images/icon-any-file.svg";
import iconCollaboration from "../images/icon-collaboration.svg";
import iconEmail from "../images/icon-email.svg";
import iconLocation from "../images/icon-location.svg";
import iconPhone from "../images/icon-phone.svg";
import iconSecurity from "../images/icon-security.svg";
import introIllustration from "../images/illustration-intro.png";
import stayProductiveIllustration from "../images/illustration-stay-productive.png";
import { FaFacebookF, FaTwitter, FaInstagram } from "react-icons/fa";
import { testimonials } from "../data/testimonials";
import { features } from "../data/features";
import Header from "../components/Header/Header";
import Hero from "../components/Hero/Hero";
import Feature from "../components/Feature/Feature";
import TestimonialCard from "../components/TestimonialCard/TestimonialCard";
import FeaturesList from "../components/FeaturesList/FeaturesList";
import TestimonialsList from "../components/TestimonialsList/TestimonialsList";
import StayProductiveSection from "../components/StayProductiveSection/StayProductiveSection";
import SignUpSection from "../components/SignUpSection/SignUpSection";
import Footer from "../components/Footer/Footer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fylo Dark Theme landing page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/joseph.ico" />
      </Head>

      <body>
        <Header />

        <main>
          <Hero />
          <FeaturesList />
          <StayProductiveSection />
          <TestimonialsList />
        </main>

        <Footer />

        {/* <footer className={styles.footerContainer}>
          <div className={styles.imageContainer}>
            <Image src={logo} alt="Footer logo" className={styles.footerLogo} />
          </div>
          <div className={styles.footerContent}>
            <div>
              <div className={styles.imageContainer}>
                <Image src={iconLocation} alt="" />
              </div>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua
              </p>
            </div>
            <div>
              <div>
                <div className={styles.imageContainer}>
                  <Image src={iconPhone} alt="" />
                </div>
                <p> +1-543-123-4567</p>
              </div>
              <div>
                <div className={styles.imageContainer}>
                  <Image src={iconEmail} alt="" />
                </div>
                <p>example@fylo.com</p>
              </div>
            </div>

            <div className={styles.links}>
              <ul>
                <li>About Us</li>
                <li>Jobs</li>
                <li>Press</li>
                <li>Blog</li>
              </ul>
              <ul>
                <li>Contact Us</li>
                <li>Terms</li>
                <li>Privacy</li>
              </ul>
            </div>

            <div className={styles.socialMedia}>
              <div>
                <FaFacebookF />
              </div>
              <div>
                <FaTwitter />
              </div>
              <div>
                <FaInstagram />
              </div>
            </div>
          </div>
        </footer> */}
      </body>
    </div>
  );
}
